apiVersion: 1

datasources:
  - name: InfluxDB_F1
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    user: ${INFLUXDB_ADMIN_USER}
    jsonData:
      dbName: f1
      httpMode: POST
    secureJsonData:
      password: ${INFLUXDB_ADMIN_PASSWORD}