[agent]
  interval = "1s"
  round_interval = true
  flush_interval = "1s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  quiet = false

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "${INFLUXDB_DB}"
  username = "${INFLUXDB_ADMIN_USER}"
  password = "${INFLUXDB_ADMIN_PASSWORD}"
  insecure_skip_verify = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics  = ["f1/monza/#"]
  qos     = 0

  data_format = "json"
  topic_tag = ""
  tag_keys = ["driver"]

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "f1/monza/+/+/+/+"
    measurement = "_/_/_/_/_/measurement"
    tags = "_/_/year/session/driver/_"